# ############################################################################################### #
#                                                                                                 #
# Fichier de configuration pour la génération d'une assertion Structure                           #
#                                                                                                 #
#                                                                                                 #
# ############################################################################################### #



# section pour les champs facultatifs 
[sec]

#
# id unique de l'agent 
# Exemple :
# nameId=employeeTest
#
nameId=agentTlsiValaModifier

#
#id facturation (optionnel)
#
idFacturation=

#
#id déléguant (optionnel)
#
idDeleguant=

#
# Chemin et fichier du convention technique
[Convention]
#Convention=C:\Users\alibih\Documents\Visual Studio 2015\Projects\Assertion_structure\doc\conv.xml
Convention=

#
# Chemin et fichier du certificat
[Certificat]
Certificat=D:\certificate.pfx




# section pour le chemin de sauvegarde du fichier XML contenant l'assertion
[Resultat]
# Exemple
#Assertion=D:\TresOpTassertStruc.xml
Assertion=




