//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLSiKitEditeur.PatientSpecificService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:si-dmp-patients", ConfigurationName="PatientSpecificService.PatientSpecificEndPoint")]
    public interface PatientSpecificEndPoint {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="output")]
        TLSiKitEditeur.PatientSpecificService.PatientAccessResponse createPatientAccess(TLSiKitEditeur.PatientSpecificService.otpChannelTypeEnum type, string canal);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="output")]
        System.Threading.Tasks.Task<TLSiKitEditeur.PatientSpecificService.PatientAccessResponse> createPatientAccessAsync(TLSiKitEditeur.PatientSpecificService.otpChannelTypeEnum type, string canal);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="output")]
        TLSiKitEditeur.PatientSpecificService.PatientListDataResponse patientList(string startDate, TLSiKitEditeur.PatientSpecificService.dateTypeEnum dateType);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="output")]
        System.Threading.Tasks.Task<TLSiKitEditeur.PatientSpecificService.PatientListDataResponse> patientListAsync(string startDate, TLSiKitEditeur.PatientSpecificService.dateTypeEnum dateType);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="output")]
        TLSiKitEditeur.PatientSpecificService.PatientAccessResponse updatePatientAccess();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="output")]
        System.Threading.Tasks.Task<TLSiKitEditeur.PatientSpecificService.PatientAccessResponse> updatePatientAccessAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="output")]
        TLSiKitEditeur.PatientSpecificService.WebServiceResponse patientOTPUpdate(TLSiKitEditeur.PatientSpecificService.otpChannelTypeEnum type, string canal, TLSiKitEditeur.PatientSpecificService.actionTypeEnum action);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="output")]
        System.Threading.Tasks.Task<TLSiKitEditeur.PatientSpecificService.WebServiceResponse> patientOTPUpdateAsync(TLSiKitEditeur.PatientSpecificService.otpChannelTypeEnum type, string canal, TLSiKitEditeur.PatientSpecificService.actionTypeEnum action);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:si-dmp-patients")]
    public enum otpChannelTypeEnum {
        
        /// <remarks/>
        SMS,
        
        /// <remarks/>
        EMAIL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:si-dmp-patients")]
    public partial class PatientAccessResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginField;
        
        private string passwordField;
        
        private string statusField;
        
        private string contextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
                this.RaisePropertyChanged("context");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:si-dmp-patients")]
    public partial class WebServiceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string contextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
                this.RaisePropertyChanged("context");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:si-dmp-patients")]
    public partial class PatientIdentifierListData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nationalIdField;
        
        private string nationalIdTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string nationalId {
            get {
                return this.nationalIdField;
            }
            set {
                this.nationalIdField = value;
                this.RaisePropertyChanged("nationalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nationalIdType {
            get {
                return this.nationalIdTypeField;
            }
            set {
                this.nationalIdTypeField = value;
                this.RaisePropertyChanged("nationalIdType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:si-dmp-patients")]
    public partial class PatientListData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PatientIdentifierListData[] patientIdentifierField;
        
        private string lastNameField;
        
        private string patronymicalNameField;
        
        private string firstNameField;
        
        private string civilityField;
        
        private string dateOfBirthField;
        
        private bool mtField;
        
        private bool messageField;
        
        private string lastAccessDateField;
        
        private string lastUpdateDateField;
        
        private string lastAddDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("patientIdentifier", Order=0)]
        public PatientIdentifierListData[] patientIdentifier {
            get {
                return this.patientIdentifierField;
            }
            set {
                this.patientIdentifierField = value;
                this.RaisePropertyChanged("patientIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string patronymicalName {
            get {
                return this.patronymicalNameField;
            }
            set {
                this.patronymicalNameField = value;
                this.RaisePropertyChanged("patronymicalName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string civility {
            get {
                return this.civilityField;
            }
            set {
                this.civilityField = value;
                this.RaisePropertyChanged("civility");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string dateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
                this.RaisePropertyChanged("dateOfBirth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool MT {
            get {
                return this.mtField;
            }
            set {
                this.mtField = value;
                this.RaisePropertyChanged("MT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string lastAccessDate {
            get {
                return this.lastAccessDateField;
            }
            set {
                this.lastAccessDateField = value;
                this.RaisePropertyChanged("lastAccessDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string lastUpdateDate {
            get {
                return this.lastUpdateDateField;
            }
            set {
                this.lastUpdateDateField = value;
                this.RaisePropertyChanged("lastUpdateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string lastAddDate {
            get {
                return this.lastAddDateField;
            }
            set {
                this.lastAddDateField = value;
                this.RaisePropertyChanged("lastAddDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:si-dmp-patients")]
    public partial class PatientListDataResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PatientListData[] patientlistDataField;
        
        private string statusField;
        
        private string contextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("patientlistData", Order=0)]
        public PatientListData[] patientlistData {
            get {
                return this.patientlistDataField;
            }
            set {
                this.patientlistDataField = value;
                this.RaisePropertyChanged("patientlistData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
                this.RaisePropertyChanged("context");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:si-dmp-patients")]
    public enum dateTypeEnum {
        
        /// <remarks/>
        LASTAUTORIZATION,
        
        /// <remarks/>
        LASTDOC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:si-dmp-patients")]
    public enum actionTypeEnum {
        
        /// <remarks/>
        AJOUT,
        
        /// <remarks/>
        MODIFICATION,
        
        /// <remarks/>
        SUPPRESSION,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PatientSpecificEndPointChannel : TLSiKitEditeur.PatientSpecificService.PatientSpecificEndPoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PatientSpecificEndPointClient : System.ServiceModel.ClientBase<TLSiKitEditeur.PatientSpecificService.PatientSpecificEndPoint>, TLSiKitEditeur.PatientSpecificService.PatientSpecificEndPoint {
        
        public PatientSpecificEndPointClient() {
        }
        
        public PatientSpecificEndPointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PatientSpecificEndPointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientSpecificEndPointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientSpecificEndPointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TLSiKitEditeur.PatientSpecificService.PatientAccessResponse createPatientAccess(TLSiKitEditeur.PatientSpecificService.otpChannelTypeEnum type, string canal) {
            return base.Channel.createPatientAccess(type, canal);
        }
        
        public System.Threading.Tasks.Task<TLSiKitEditeur.PatientSpecificService.PatientAccessResponse> createPatientAccessAsync(TLSiKitEditeur.PatientSpecificService.otpChannelTypeEnum type, string canal) {
            return base.Channel.createPatientAccessAsync(type, canal);
        }
        
        public TLSiKitEditeur.PatientSpecificService.PatientListDataResponse patientList(string startDate, TLSiKitEditeur.PatientSpecificService.dateTypeEnum dateType) {
            return base.Channel.patientList(startDate, dateType);
        }
        
        public System.Threading.Tasks.Task<TLSiKitEditeur.PatientSpecificService.PatientListDataResponse> patientListAsync(string startDate, TLSiKitEditeur.PatientSpecificService.dateTypeEnum dateType) {
            return base.Channel.patientListAsync(startDate, dateType);
        }
        
        public TLSiKitEditeur.PatientSpecificService.PatientAccessResponse updatePatientAccess() {
            return base.Channel.updatePatientAccess();
        }
        
        public System.Threading.Tasks.Task<TLSiKitEditeur.PatientSpecificService.PatientAccessResponse> updatePatientAccessAsync() {
            return base.Channel.updatePatientAccessAsync();
        }
        
        public TLSiKitEditeur.PatientSpecificService.WebServiceResponse patientOTPUpdate(TLSiKitEditeur.PatientSpecificService.otpChannelTypeEnum type, string canal, TLSiKitEditeur.PatientSpecificService.actionTypeEnum action) {
            return base.Channel.patientOTPUpdate(type, canal, action);
        }
        
        public System.Threading.Tasks.Task<TLSiKitEditeur.PatientSpecificService.WebServiceResponse> patientOTPUpdateAsync(TLSiKitEditeur.PatientSpecificService.otpChannelTypeEnum type, string canal, TLSiKitEditeur.PatientSpecificService.actionTypeEnum action) {
            return base.Channel.patientOTPUpdateAsync(type, canal, action);
        }
    }
}
