//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLSiKitEditeur.HabilitationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:si-dmp-habilitations", ConfigurationName="HabilitationService.HabilitationsEndPoint")]
    public interface HabilitationsEndPoint {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:hl7-org:v3:listAuthorizationByPatient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="output")]
        TLSiKitEditeur.HabilitationService.AuthorizationByPatientResponse listAuthorizationByPatient(TLSiKitEditeur.HabilitationService.modeType mode);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:hl7-org:v3:listAuthorizationByPatient", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="output")]
        System.Threading.Tasks.Task<TLSiKitEditeur.HabilitationService.AuthorizationByPatientResponse> listAuthorizationByPatientAsync(TLSiKitEditeur.HabilitationService.modeType mode);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:hl7-org:v3:setAuthorization", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="output")]
        TLSiKitEditeur.HabilitationService.WebServiceResponse setAuthorization(TLSiKitEditeur.HabilitationService.actionType action, TLSiKitEditeur.HabilitationService.roleType role);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:hl7-org:v3:setAuthorization", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="output")]
        System.Threading.Tasks.Task<TLSiKitEditeur.HabilitationService.WebServiceResponse> setAuthorizationAsync(TLSiKitEditeur.HabilitationService.actionType action, TLSiKitEditeur.HabilitationService.roleType role);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:si-dmp-habilitations")]
    public enum modeType {
        
        /// <remarks/>
        ACTIVE,
        
        /// <remarks/>
        INTERDITE,
        
        /// <remarks/>
        TOUTE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:si-dmp-habilitations")]
    public partial class AuthorizationByPatientResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AuthorizationByPatient[] listOfAuthorizationByPatientField;
        
        private string statusField;
        
        private string contextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listOfAuthorizationByPatient", Order=0)]
        public AuthorizationByPatient[] listOfAuthorizationByPatient {
            get {
                return this.listOfAuthorizationByPatientField;
            }
            set {
                this.listOfAuthorizationByPatientField = value;
                this.RaisePropertyChanged("listOfAuthorizationByPatient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
                this.RaisePropertyChanged("context");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:si-dmp-habilitations")]
    public partial class AuthorizationByPatient : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nationalIdField;
        
        private string nationalIdTypeField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string[] codeSpecialityField;
        
        private string[] libSpecialityField;
        
        private string startOfAuthorizationField;
        
        private string lastActionDateField;
        
        private modeType modeField;
        
        private bool modeFieldSpecified;
        
        private roleType[] specificRightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string nationalId {
            get {
                return this.nationalIdField;
            }
            set {
                this.nationalIdField = value;
                this.RaisePropertyChanged("nationalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nationalIdType {
            get {
                return this.nationalIdTypeField;
            }
            set {
                this.nationalIdTypeField = value;
                this.RaisePropertyChanged("nationalIdType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codeSpeciality", Order=4)]
        public string[] codeSpeciality {
            get {
                return this.codeSpecialityField;
            }
            set {
                this.codeSpecialityField = value;
                this.RaisePropertyChanged("codeSpeciality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("libSpeciality", Order=5)]
        public string[] libSpeciality {
            get {
                return this.libSpecialityField;
            }
            set {
                this.libSpecialityField = value;
                this.RaisePropertyChanged("libSpeciality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string startOfAuthorization {
            get {
                return this.startOfAuthorizationField;
            }
            set {
                this.startOfAuthorizationField = value;
                this.RaisePropertyChanged("startOfAuthorization");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string lastActionDate {
            get {
                return this.lastActionDateField;
            }
            set {
                this.lastActionDateField = value;
                this.RaisePropertyChanged("lastActionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public modeType mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
                this.RaisePropertyChanged("mode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modeSpecified {
            get {
                return this.modeFieldSpecified;
            }
            set {
                this.modeFieldSpecified = value;
                this.RaisePropertyChanged("modeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("specificRight", Order=9)]
        public roleType[] specificRight {
            get {
                return this.specificRightField;
            }
            set {
                this.specificRightField = value;
                this.RaisePropertyChanged("specificRight");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:si-dmp-habilitations")]
    public enum roleType {
        
        /// <remarks/>
        MEDECIN_TRAITANT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:si-dmp-habilitations")]
    public partial class WebServiceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string contextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
                this.RaisePropertyChanged("context");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:si-dmp-habilitations")]
    public enum actionType {
        
        /// <remarks/>
        AJOUT,
        
        /// <remarks/>
        SUPPRESSION,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HabilitationsEndPointChannel : TLSiKitEditeur.HabilitationService.HabilitationsEndPoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HabilitationsEndPointClient : System.ServiceModel.ClientBase<TLSiKitEditeur.HabilitationService.HabilitationsEndPoint>, TLSiKitEditeur.HabilitationService.HabilitationsEndPoint {
        
        public HabilitationsEndPointClient() {
        }
        
        public HabilitationsEndPointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HabilitationsEndPointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HabilitationsEndPointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HabilitationsEndPointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TLSiKitEditeur.HabilitationService.AuthorizationByPatientResponse listAuthorizationByPatient(TLSiKitEditeur.HabilitationService.modeType mode) {
            return base.Channel.listAuthorizationByPatient(mode);
        }
        
        public System.Threading.Tasks.Task<TLSiKitEditeur.HabilitationService.AuthorizationByPatientResponse> listAuthorizationByPatientAsync(TLSiKitEditeur.HabilitationService.modeType mode) {
            return base.Channel.listAuthorizationByPatientAsync(mode);
        }
        
        public TLSiKitEditeur.HabilitationService.WebServiceResponse setAuthorization(TLSiKitEditeur.HabilitationService.actionType action, TLSiKitEditeur.HabilitationService.roleType role) {
            return base.Channel.setAuthorization(action, role);
        }
        
        public System.Threading.Tasks.Task<TLSiKitEditeur.HabilitationService.WebServiceResponse> setAuthorizationAsync(TLSiKitEditeur.HabilitationService.actionType action, TLSiKitEditeur.HabilitationService.roleType role) {
            return base.Channel.setAuthorizationAsync(action, role);
        }
    }
}
