//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLSiKitEditeur.PatientCertificationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceResponse", Namespace="urn:si-dmp-patients")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TLSiKitEditeur.PatientCertificationService.PatientCertificationResponse))]
    public partial class WebServiceResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string context {
            get {
                return this.contextField;
            }
            set {
                if ((object.ReferenceEquals(this.contextField, value) != true)) {
                    this.contextField = value;
                    this.RaisePropertyChanged("context");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientCertificationResponse", Namespace="urn:si-dmp-patients")]
    [System.SerializableAttribute()]
    public partial class PatientCertificationResponse : TLSiKitEditeur.PatientCertificationService.WebServiceResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nirIndividuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prenomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomUsuelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomPatronymiqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dateNaissanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nirIndividu {
            get {
                return this.nirIndividuField;
            }
            set {
                if ((object.ReferenceEquals(this.nirIndividuField, value) != true)) {
                    this.nirIndividuField = value;
                    this.RaisePropertyChanged("nirIndividu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string prenom {
            get {
                return this.prenomField;
            }
            set {
                if ((object.ReferenceEquals(this.prenomField, value) != true)) {
                    this.prenomField = value;
                    this.RaisePropertyChanged("prenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nomUsuel {
            get {
                return this.nomUsuelField;
            }
            set {
                if ((object.ReferenceEquals(this.nomUsuelField, value) != true)) {
                    this.nomUsuelField = value;
                    this.RaisePropertyChanged("nomUsuel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nomPatronymique {
            get {
                return this.nomPatronymiqueField;
            }
            set {
                if ((object.ReferenceEquals(this.nomPatronymiqueField, value) != true)) {
                    this.nomPatronymiqueField = value;
                    this.RaisePropertyChanged("nomPatronymique");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string dateNaissance {
            get {
                return this.dateNaissanceField;
            }
            set {
                if ((object.ReferenceEquals(this.dateNaissanceField, value) != true)) {
                    this.dateNaissanceField = value;
                    this.RaisePropertyChanged("dateNaissance");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:si-dmp-patients", ConfigurationName="PatientCertificationService.PatientCertificationEndPoint")]
    public interface PatientCertificationEndPoint {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément nirOD de l'espace de noms urn:si-dmp-patients n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        TLSiKitEditeur.PatientCertificationService.identityCertificationResponse identityCertification(TLSiKitEditeur.PatientCertificationService.identityCertification request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TLSiKitEditeur.PatientCertificationService.identityCertificationResponse> identityCertificationAsync(TLSiKitEditeur.PatientCertificationService.identityCertification request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class identityCertification {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="identityCertification", Namespace="urn:si-dmp-patients", Order=0)]
        public TLSiKitEditeur.PatientCertificationService.identityCertificationBody Body;
        
        public identityCertification() {
        }
        
        public identityCertification(TLSiKitEditeur.PatientCertificationService.identityCertificationBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:si-dmp-patients")]
    public partial class identityCertificationBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nirOD;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dateNaissance;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int rangNaissance;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nirIndividu;
        
        public identityCertificationBody() {
        }
        
        public identityCertificationBody(string nirOD, string dateNaissance, int rangNaissance, string nirIndividu) {
            this.nirOD = nirOD;
            this.dateNaissance = dateNaissance;
            this.rangNaissance = rangNaissance;
            this.nirIndividu = nirIndividu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class identityCertificationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="identityCertificationResponse", Namespace="urn:si-dmp-patients", Order=0)]
        public TLSiKitEditeur.PatientCertificationService.identityCertificationResponseBody Body;
        
        public identityCertificationResponse() {
        }
        
        public identityCertificationResponse(TLSiKitEditeur.PatientCertificationService.identityCertificationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:si-dmp-patients")]
    public partial class identityCertificationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TLSiKitEditeur.PatientCertificationService.PatientCertificationResponse output;
        
        public identityCertificationResponseBody() {
        }
        
        public identityCertificationResponseBody(TLSiKitEditeur.PatientCertificationService.PatientCertificationResponse output) {
            this.output = output;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PatientCertificationEndPointChannel : TLSiKitEditeur.PatientCertificationService.PatientCertificationEndPoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PatientCertificationEndPointClient : System.ServiceModel.ClientBase<TLSiKitEditeur.PatientCertificationService.PatientCertificationEndPoint>, TLSiKitEditeur.PatientCertificationService.PatientCertificationEndPoint {
        
        public PatientCertificationEndPointClient() {
        }
        
        public PatientCertificationEndPointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PatientCertificationEndPointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientCertificationEndPointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientCertificationEndPointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TLSiKitEditeur.PatientCertificationService.identityCertificationResponse TLSiKitEditeur.PatientCertificationService.PatientCertificationEndPoint.identityCertification(TLSiKitEditeur.PatientCertificationService.identityCertification request) {
            return base.Channel.identityCertification(request);
        }
        
        public TLSiKitEditeur.PatientCertificationService.PatientCertificationResponse identityCertification(string nirOD, string dateNaissance, int rangNaissance, string nirIndividu) {
            TLSiKitEditeur.PatientCertificationService.identityCertification inValue = new TLSiKitEditeur.PatientCertificationService.identityCertification();
            inValue.Body = new TLSiKitEditeur.PatientCertificationService.identityCertificationBody();
            inValue.Body.nirOD = nirOD;
            inValue.Body.dateNaissance = dateNaissance;
            inValue.Body.rangNaissance = rangNaissance;
            inValue.Body.nirIndividu = nirIndividu;
            TLSiKitEditeur.PatientCertificationService.identityCertificationResponse retVal = ((TLSiKitEditeur.PatientCertificationService.PatientCertificationEndPoint)(this)).identityCertification(inValue);
            return retVal.Body.output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TLSiKitEditeur.PatientCertificationService.identityCertificationResponse> TLSiKitEditeur.PatientCertificationService.PatientCertificationEndPoint.identityCertificationAsync(TLSiKitEditeur.PatientCertificationService.identityCertification request) {
            return base.Channel.identityCertificationAsync(request);
        }
        
        public System.Threading.Tasks.Task<TLSiKitEditeur.PatientCertificationService.identityCertificationResponse> identityCertificationAsync(string nirOD, string dateNaissance, int rangNaissance, string nirIndividu) {
            TLSiKitEditeur.PatientCertificationService.identityCertification inValue = new TLSiKitEditeur.PatientCertificationService.identityCertification();
            inValue.Body = new TLSiKitEditeur.PatientCertificationService.identityCertificationBody();
            inValue.Body.nirOD = nirOD;
            inValue.Body.dateNaissance = dateNaissance;
            inValue.Body.rangNaissance = rangNaissance;
            inValue.Body.nirIndividu = nirIndividu;
            return ((TLSiKitEditeur.PatientCertificationService.PatientCertificationEndPoint)(this)).identityCertificationAsync(inValue);
        }
    }
}
